baseurl = "/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Edu Gonzalo Almorox"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Quantitative research scientist | Economist | Data Analyst"
  logo = "img/portrait.jpg"
  #favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Edu Gonzalo Almorox"
  #website = "edugonzaloweb"
  email = "eduardogonzaloalmorox@gmail.com"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "edugonzaloalmorox"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "EdudinGonzalo"
  #reddit = "username"
  linkedin = "eduardo-gonzalo-almorox-5b8b4955"
  #xing = "username"
  stackoverflow = "users/5823126/edu"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #∫500px = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "research"
    name = "Research"
    weight = 2

[[menu.main]]
    parent = "research"
    name = "Publications"
    url = "post/publications"
    weight = 1

[[menu.main]]
    parent = "research"
    name = "Work in progress"
    url = "post/work-in-progress"
    weight = 2

[[menu.main]]
    parent = "research"
    name = "Other projects"
    url = "post/projects"
    weight = 3
    
[[menu.main]]
    name = "CV"
    url = "page/resume/"
    weight = 4


