---
title: Projects
author: ''
date: 2018-04-23T21:13:14-05:00
slug: projects
categories: []
tags: []
subtitle: ''
---

## Tracking the quality of social care


This is a [shiny app](https://edugonzaloalmorox.shinyapps.io/care-homes-quality/) presenting information referred to care homes in England. It is composed of three main tabs and uses data from the [Care Quality Commission](https://www.cqc.org.uk/about-us/transparency/using-cqc-data). 

- `Data`: Shows information of current active care homes (as to April 2019) on their quality ratings. It enables to track care all quality inspections undertaken in a care home since 2014. `number_inspection` and `total_inspections_category` provide information concerning the number of inspections taken in a care home.


- `Inspections per year`: Represents the number of quality inspections carried out at regional level over the period 2015-2019. 

- `Ratings per quality dimension`: Show the number of care homes rated: Outstanding, Good, Requires Improvement or Inadequate, for each quality category evaluated and each local authority in England. 


## Hello in the Shiny world


As part of [tidytuesday](https://github.com/rfordatascience/tidytuesday) project, I build a (rather) simple [shiny app](https://edugonzaloalmorox.shinyapps.io/test-stops/) to visualise how the arrest rates, search rates and stop rates, vary across several states and driver's race. The data come from the Stanford Open Policing Project on policing activity in several US states. 