---
title: Work in progress
author: ''
date: 2018-11-04
slug: work-in-progress
categories: []
tags: []
subtitle: ''
---

These are the **working papers** of past and ongoing projects 

- [The role of queuing models in economic evaluation: lessons from an illustrative case study of emergency care](https://pdfs.semanticscholar.org/260c/4eaede4a2b4104b2cf2331f6b7db5226d5dc.pdf) _Newcastle Health Economics Group working paper series_. HEG2015_03 **2015** (with Alexandru Lucian Gaianu and Luke Vale)

- [The effect of house prices on the long-term care market: Evidence from England](/pdf/care_homes_houseprices_jan19.pdf) **2017** (with Volodymyr Bilotkach, Nils Braakmann and John Wildman)


- [Local budgets and care homes quality in England: a duration analysis](/pdf/duration_quality_jan19.pdf) **2018** (with  Nils Braakmann and John Wildman)

- [The effect of care home closures on the quality of care homes nearby](/pdf/care_homes_closures_mar19.pdf) **2018** - **Job Market Paper**

- How public information affects online reviews? Insights from long term care

- Exploring clustering unhealthy hot food outlets around schools in England: A secondary data analysis (with Louise Gray, Amelia Lake and Heather Brown)



